import { Project } from './mock-project';

export const projects: Project[] = [
	{
		"id": "bitconnect",
		"name": "BITCONNECT",
		"rating": "5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "7-Jan-17",
		"end": "ENDED",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "./assets/img/logo/bitconnect.png",
		"is_presale": "0",
		"description": "short desc",
		"media_url": "",
		"goal": "$1,000,000",
		"website": "",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": ""
	},
	{
		"id": "etherbanking",
		"name": "ETHERBANKING",
		"rating": "4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "10-Jan-18",
		"end": "10-Feb-18",
		"status": "UPCOMING",
		"betting": "NORMAL",
		"logo": "./assets/img/logo/etherbanking.png",
		"is_presale": "0",
		"description": "short desc",
		"media_url": "",
		"goal": "$1,000,000",
		"website": "",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": ""
	},
	{
		"id": "magiccoin",
		"name": "MAGICCOIN",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "24-Dec-17",
		"end": "24-Jan-18",
		"status": "ACTIVE",
		"betting": "BIG $$$",
		"logo": "./assets/img/logo/magiccoin.png",
		"is_presale": "0",
		"description": "short desc",
		"media_url": "",
		"goal": "$1,000,000",
		"website": "",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": ""
	},
	{
		"id": "laser",
		"name": "LASER",
		"rating": "0",
		"hype": "SCAM",
		"scam": "SCAM",
		"moon": "SCAM",
		"start": "1-Dec-17",
		"end": "1-Jan-18",
		"status": "SCAM",
		"betting": "SCAM",
		"logo": "./assets/img/logo/laser.png",
		"is_presale": "0",
		"description": "short desc",
		"media_url": "",
		"goal": "$1,000,000",
		"website": "",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": ""
	}
];
