import { Project } from './mock-project';

export const projects: Project[] = [
	{
		"id": "bitconnect",
		"name": "BITCONNECT",
		"rating": "5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "7-Jan-17",
		"end": "ENDED",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "bitconnect.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://bitconnect.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "hextracoin",
		"name": "HEXTRACOIN",
		"rating": "5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "1-Oct-17",
		"end": "30-Oct-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "hextracoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://hextracoin.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "davor",
		"name": "DAVOR",
		"rating": "5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "6-Nov-17",
		"end": "19-Nov-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "davor.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://davor.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "magiccoin",
		"name": "MAGICCOIN",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "24-Dec-17",
		"end": "24-Jan-18",
		"status": "ACTIVE",
		"betting": "BIG $$$",
		"logo": "magiccoin.png",
		"is_presale": "0",
		"has_detail": "1",
		"description": "POS Magiccoin is the first trading platform dedicated to altcoins based on proofof-stake (from here on will be called POS coins).",
		"media_url": "https://www.youtube.com/embed/il6-apng_yo",
		"goal": "10000000",
		"website": "https://magiccoin.io",
		"whitepaper": "https://magiccoin.io/upload/document/whitepaper_en.pdf",
		"github": "",
		"twitter": "https://twitter.com/Magiccoinio",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "https://www.youtube.com/watch?v=il6-apng_yo",
		"ticker": "MAGE",
		"token_type": "Coin",
		"price": "1 MAGE = 5.9915 USD",
		"total_token": "44,000,000",
		"available_token_sale": "3,600,000",
		"ref_bonus": "N/A",
		"accepts": "BTC",
		"social_activity_level": "HIGH",
		"number_team_member": "N/A",
		"ssl_certificate": "yes",
		"desktop_wallet": "yes",
		"internal_exchange": "N/A",
		"external_exchange": "yes"
	},
	{
		"id": "homeblock",
		"name": "HOMEBLOCK",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "4-Nov-17",
		"end": "23-Nov-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "homeblockcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://www.homeblockcoin.com/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "exacoin",
		"name": "EXACOIN",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "12-Dec-17",
		"end": "30-Nov-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "exacoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://exacoin.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "areszcoin",
		"name": "ARESZCOIN",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "22-Nov_2017",
		"end": "21-Dec_2017",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "areszcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://www.areszcoin.com",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "libracoin",
		"name": "LIBRACOIN",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "11-Dec-17",
		"end": "21-Dec_2018",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "libracoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://libracoin.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "bitfinite",
		"name": "BITFINITE",
		"rating": "4.7",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "22-Dec-17",
		"end": "17-Jan-18",
		"status": "ACTIVE",
		"betting": "BIG $$$",
		"logo": "bitfinite.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://www.bitfinite.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "ucoincash",
		"name": "UCOINCASH",
		"rating": "4.6",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "15-Nov-17",
		"end": "15-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "ucoincash.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://ucoincash.co/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "unixcoin",
		"name": "UNIXCOIN",
		"rating": "4.6",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "26-Nov-17",
		"end": "20-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "unixcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://unixcoin.com/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "regalcoin",
		"name": "REGALCOIN",
		"rating": "4.5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "1-Sep-17",
		"end": "1-Oct-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "regalcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://regalcoin.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "firstcoin",
		"name": "FIRSTCOIN",
		"rating": "4.5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "1-Mar-17",
		"end": "1-Apr-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "firstcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://firstcoin.club",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "ideacoin",
		"name": "IDEACOIN",
		"rating": "4.5",
		"hype": "VERY HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "20-Nov-17",
		"end": "19-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "ideacoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://ico.ideacoin.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "monyx",
		"name": "MONYX",
		"rating": "4.5",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "25-Dec-17",
		"end": "8-Jan-18",
		"status": "ACTIVE",
		"betting": "NORMAL",
		"logo": "monyx.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://monyx.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "ecomcash",
		"name": "ECOMCASH",
		"rating": "4.4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "VERY HIGH",
		"start": "26-Dec-17",
		"end": "20-Jan-18",
		"status": "ACTIVE",
		"betting": "NORMAL",
		"logo": "ecomcash.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://ecomcash.io/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "cointeum",
		"name": "COINTEUM",
		"rating": "4.2",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "15-Dec-17",
		"end": "31-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "cointeum.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://cointeum.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "etherbanking",
		"name": "ETHERBANKING",
		"rating": "4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "10-Jan-18",
		"end": "10-Feb-18",
		"status": "UPCOMING",
		"betting": "NORMAL",
		"logo": "etherbanking.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://etherbanking.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "bitserial",
		"name": "BITSERIAL",
		"rating": "4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "15-Oct-17",
		"end": "12-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "bitserial.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://bitserial.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "tex",
		"name": "TEX",
		"rating": "4",
		"hype": "MID",
		"scam": "VERY LOW",
		"moon": "LOW",
		"start": "9-Nov-17",
		"end": "9-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "tex.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://www.tex.io/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "numivcoin",
		"name": "NUMIVCOIN",
		"rating": "4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "19-Nov-17",
		"end": "19-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "numivcoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://numivcoin.com",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "eigencoin",
		"name": "EIGENCOIN",
		"rating": "4",
		"hype": "HIGH",
		"scam": "VERY LOW",
		"moon": "HIGH",
		"start": "4-Dec-17",
		"end": "19-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "eigencoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://www.eigencoin.co",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "loancoin",
		"name": "LOANCOIN",
		"rating": "3.9",
		"hype": "HIGH",
		"scam": "LOW",
		"moon": "HIGH",
		"start": "4-Dec-17",
		"end": "3-Jan-18",
		"status": "ACTIVE",
		"betting": "VERY SMALL",
		"logo": "loancoin.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://loancoin.com",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "polynetwork",
		"name": "POLYNETWORK",
		"rating": "3.9",
		"hype": "MID",
		"scam": "VERY LOW",
		"moon": "MID",
		"start": "1-Nov-17",
		"end": "20-Nov-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "polynetwork.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://polynetwork.org/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "v-one",
		"name": "V-ONE",
		"rating": "3.9",
		"hype": "HIGH",
		"scam": "LOW",
		"moon": "MID",
		"start": "29-Nov-17",
		"end": "29-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "v-one.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://v-one.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "goldreward ",
		"name": "GOLDREWARD ",
		"rating": "3.9",
		"hype": "HIGH",
		"scam": "LOW",
		"moon": "MID",
		"start": "28-Oct-17",
		"end": "25-Nov-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "goldreward.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://goldreward.io/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "goldgate",
		"name": "GOLDGATE",
		"rating": "3.8",
		"hype": "HIGH",
		"scam": "LOW",
		"moon": "MID",
		"start": "25-Nov-17",
		"end": "16-Dec-17",
		"status": "ENDED",
		"betting": "ICO ENDED",
		"logo": "goldgate.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://goldgate.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "laser",
		"name": "LASER",
		"rating": "0",
		"hype": "SCAM",
		"scam": "SCAM",
		"moon": "SCAM",
		"start": "1-Dec-17",
		"end": "1-Jan-18",
		"status": "SCAM",
		"betting": "SCAM",
		"logo": "laser.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://laser.online/",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	},
	{
		"id": "ifan",
		"name": "IFAN",
		"rating": "0",
		"hype": "SCAM",
		"scam": "SCAM",
		"moon": "SCAM",
		"start": "18-Nov-17",
		"end": "9-Dec-17",
		"status": "SCAM",
		"betting": "SCAM",
		"logo": "ifan.png",
		"is_presale": "0",
		"has_detail": "0",
		"description": "",
		"media_url": "",
		"goal": "",
		"website": "https://ifan.io",
		"whitepaper": "",
		"github": "",
		"twitter": "",
		"telegram": "",
		"bitcointalk": "",
		"youtube": "",
		"ticker": "",
		"token_type": "",
		"price": "",
		"total_token": "",
		"available_token_sale": "",
		"ref_bonus": "",
		"accepts": "",
		"social_activity_level": "",
		"number_team_member": "",
		"ssl_certificate": "",
		"desktop_wallet": "",
		"internal_exchange": "",
		"external_exchange": "N/A"
	}
];
